from .angle_prompt_en import NODE_CLASS_MAPPINGS as EN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EN_DISPLAY_MAPPINGS
from .angle_prompt_cn import NODE_CLASS_MAPPINGS as CN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CN_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**EN_MAPPINGS, **CN_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**EN_DISPLAY_MAPPINGS, **CN_DISPLAY_MAPPINGS}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
